apiVersion: v1
kind: Namespace
metadata:
  name: fitness-app
 
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fitness-keyvault-csi
  namespace: fitness-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
 
    # IMPORTANT: this must be the CSI add-on managed identity CLIENT ID
    userAssignedIdentityID: "<CSI_CLIENT_ID>"
 
    # Key Vault name only, not full URL
    keyvaultName: "<YOUR_KEYVAULT_NAME>"
 
    # Azure tenant ID
    tenantId: "<TENANT_ID>"
 
    objects: |
      array:
        - |
          objectName: <DB-ConnectionString-KeyVault-KeyName>
          objectType: secret
          objectVersion: ""
 
  secretObjects:
    - secretName: cosmos-db-secret
      type: Opaque
      data:
        - objectName: <DB-ConnectionString-KeyVault-KeyName>
          key: MONGODB_URI
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-app
  namespace: fitness-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fitness-tracker-app
  template:
    metadata:
      labels:
        app: fitness-tracker-app
    spec:
      containers:
        - name: fitness-tracker-app
          image: pulkit197/fitness_tracker-master-copy3-fitness-app:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
          ports:
            - containerPort: 5000
 
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: MONGODB_URI
 
            - name: PORT
              value: "5000"
 
            - name: NODE_ENV
              value: "production"
 
          volumeMounts:
            - name: keyvault-secrets
              mountPath: "/mnt/secrets-store"
              readOnly: true
 
      volumes:
        - name: keyvault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: fitness-keyvault-csi
 
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
  namespace: fitness-app
spec:
  selector:
    app: fitness-tracker-app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer