apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: relationship-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: change-intelligence-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-worker
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbox-relay
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: 98e5b955-8bc7-4e2a-86b1-eb770c35de38
automountServiceAccountToken: true
