apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jd-carenest-kv-secrets
  namespace: carenest-dev
spec:
  provider: azure
  secretObjects:
  - secretName: carenest-secrets
    type: Opaque
    data:
    - objectName: cosmos-connection-string
      key: MONGO_URI
    - objectName: cosmos-connection-string
      key: MONGODB_URI
    - objectName: storage-connection-string
      key: STORAGE_CONNECTION_STRING
    - objectName: servicebus-connection-string
      key: SERVICEBUS_CONNECTION_STRING
    - objectName: openai-api-key
      key: AZURE_OPENAI_KEY
    - objectName: openai-endpoint
      key: AZURE_OPENAI_ENDPOINT
    - objectName: language-api-key
      key: AZURE_LANGUAGE_KEY
    - objectName: language-endpoint
      key: AZURE_LANGUAGE_ENDPOINT
    - objectName: entra-client-id
      key: ENTRA_CLIENT_ID
    - objectName: entra-tenant-id
      key: ENTRA_TENANT_ID
    - objectName: entra-client-secret
      key: ENTRA_CLIENT_SECRET
    - objectName: jwt-secret
      key: JWT_SECRET
    - objectName: jwt-expires-in
      key: JWT_EXPIRES_IN
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2d0da740-670c-4ae8-bccd-7ec118c2679e"
    keyvaultName: "jd-carenest-kv"
    objects: |
      array:
        - |
          objectName: cosmos-connection-string
          objectType: secret
        - |
          objectName: storage-connection-string
          objectType: secret
        - |
          objectName: servicebus-connection-string
          objectType: secret
        - |
          objectName: openai-api-key
          objectType: secret
        - |
          objectName: openai-endpoint
          objectType: secret
        - |
          objectName: language-api-key
          objectType: secret
        - |
          objectName: language-endpoint
          objectType: secret
        - |
          objectName: entra-client-id
          objectType: secret
        - |
          objectName: entra-tenant-id
          objectType: secret
        - |
          objectName: entra-client-secret
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: jwt-expires-in
          objectType: secret
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394" # Can be omitted or populated if known
