apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jd-carenest-new-kv-secrets
  namespace: carenest-dev
spec:
  provider: azure
  secretObjects:
  - secretName: carenest-secrets
    type: Opaque
    data:
    - objectName: cosmos-connection-string
      key: MONGO_URI
    - objectName: cosmos-connection-string
      key: MONGODB_URI
    - objectName: storage-connection-string
      key: STORAGE_CONNECTION_STRING
    - objectName: servicebus-connection-string
      key: SERVICEBUS_CONNECTION_STRING
    - objectName: openai-api-key
      key: AZURE_OPENAI_KEY
    - objectName: openai-endpoint
      key: AZURE_OPENAI_ENDPOINT
    - objectName: language-api-key
      key: AZURE_LANGUAGE_KEY
    - objectName: language-endpoint
      key: AZURE_LANGUAGE_ENDPOINT
    - objectName: jwt-secret
      key: JWT_SECRET
    - objectName: jwt-expires-in
      key: JWT_EXPIRES_IN
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "bf8f80b4-074a-4bc0-bf61-e37dfc8bd5db"
    keyvaultName: "jd-carenest-new-kv"
    objects: |
      array:
        - |
          objectName: cosmos-connection-string
          objectType: secret
        - |
          objectName: storage-connection-string
          objectType: secret
        - |
          objectName: servicebus-connection-string
          objectType: secret
        - |
          objectName: openai-api-key
          objectType: secret
        - |
          objectName: openai-endpoint
          objectType: secret
        - |
          objectName: language-api-key
          objectType: secret
        - |
          objectName: language-endpoint
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: jwt-expires-in
          objectType: secret
    tenantId: "c0175156-9f9f-41ce-9694-2ad94cef2810"
